"""init

Revision ID: 8aaa922367cf
Revises: 
Create Date: 2026-04-25 21:27:26.816579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aaa922367cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('selected_model', sa.String(length=64), nullable=False),
    sa.Column('selected_reranker_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_sessions_updated_at', 'chat_sessions', ['updated_at'], unique=False)
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('incident_report_roles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('assigned_by', sa.String(length=32), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_table('incident_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ref_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('reporter_id', sa.String(length=32), nullable=False),
    sa.Column('assignee_id', sa.String(length=32), nullable=True),
    sa.Column('verifier_id', sa.String(length=32), nullable=True),
    sa.Column('system', sa.String(length=100), nullable=True),
    sa.Column('site_id', sa.String(length=100), nullable=True),
    sa.Column('fault_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incident_reports_reporter_id', 'incident_reports', ['reporter_id'], unique=False)
    op.create_index('idx_incident_reports_status', 'incident_reports', ['status'], unique=False)
    op.create_index('idx_incident_reports_updated_at', 'incident_reports', ['updated_at'], unique=False)
    op.create_index(op.f('ix_incident_reports_ref_no'), 'incident_reports', ['ref_no'], unique=True)
    op.create_table('incident_audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incident_audit_logs_report_id', 'incident_audit_logs', ['report_id'], unique=False)
    op.create_table('incident_comments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['incident_comments.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['incident_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incident_comments_report_id', 'incident_comments', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_incident_comments_report_id', table_name='incident_comments')
    op.drop_table('incident_comments')
    op.drop_index('idx_incident_audit_logs_report_id', table_name='incident_audit_logs')
    op.drop_table('incident_audit_logs')
    op.drop_index(op.f('ix_incident_reports_ref_no'), table_name='incident_reports')
    op.drop_index('idx_incident_reports_updated_at', table_name='incident_reports')
    op.drop_index('idx_incident_reports_status', table_name='incident_reports')
    op.drop_index('idx_incident_reports_reporter_id', table_name='incident_reports')
    op.drop_table('incident_reports')
    op.drop_table('incident_report_roles')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.drop_index('idx_chat_sessions_updated_at', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
